onboarding = false

[theme]
name = "catppuccin"
auto_switch = true
light_name = "catppuccin-latte"
dark_name = "catppuccin"

[terminal]
default_shell = "/run/current-system/sw/bin/fish"
shell_mode = "login"
new_cwd = "follow"

[keys]
split_vertical = ["prefix+v", "prefix+|"]
split_horizontal = "prefix+minus"
previous_workspace = "prefix+["
next_workspace = "prefix+]"

[ui]
show_agent_labels_on_pane_borders = true

[ui.toast]
delivery = "system"
delay_seconds = 1

[ui.sound]
enabled = true
